blueprint:
  name: Aqara H2 4-Button Switch (ZHA)
  description: >
    Handle all buttons and press types from Aqara H2 (lumi.switch.agl006)
    using ZHA events (command format: "<button>_<press_type>").
  domain: automation
  input:
    zha_device:
      name: Aqara H2 device
      selector:
        device:
          integration: zha

    button_1_single:
      name: Button 1 - Single press
      default: []
      selector:
        action: {}
    button_1_double:
      name: Button 1 - Double press
      default: []
      selector:
        action: {}
    button_1_hold:
      name: Button 1 - Hold
      default: []
      selector:
        action: {}
    button_1_release:
      name: Button 1 - Release
      default: []
      selector:
        action: {}

    button_2_single:
      name: Button 2 - Single press
      default: []
      selector:
        action: {}
    button_2_double:
      name: Button 2 - Double press
      default: []
      selector:
        action: {}
    button_2_hold:
      name: Button 2 - Hold
      default: []
      selector:
        action: {}
    button_2_release:
      name: Button 2 - Release
      default: []
      selector:
        action: {}

    button_3_single:
      name: Button 3 - Single press
      default: []
      selector:
        action: {}
    button_3_double:
      name: Button 3 - Double press
      default: []
      selector:
        action: {}
    button_3_hold:
      name: Button 3 - Hold
      default: []
      selector:
        action: {}
    button_3_release:
      name: Button 3 - Release
      default: []
      selector:
        action: {}

    button_4_single:
      name: Button 4 - Single press
      default: []
      selector:
        action: {}
    button_4_double:
      name: Button 4 - Double press
      default: []
      selector:
        action: {}
    button_4_hold:
      name: Button 4 - Hold
      default: []
      selector:
        action: {}
    button_4_release:
      name: Button 4 - Release
      default: []
      selector:
        action: {}

mode: single

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input zha_device

variables:
  command: "{{ trigger.event.data.command }}"

action:
  - choose:
      # Button 1
      - conditions: "{{ command == '1_single' }}"
        sequence: !input button_1_single
      - conditions: "{{ command == '1_double' }}"
        sequence: !input button_1_double
      - conditions: "{{ command == '1_hold' }}"
        sequence: !input button_1_hold
      - conditions: "{{ command == '1_release' }}"
        sequence: !input button_1_release

      # Button 2
      - conditions: "{{ command == '2_single' }}"
        sequence: !input button_2_single
      - conditions: "{{ command == '2_double' }}"
        sequence: !input button_2_double
      - conditions: "{{ command == '2_hold' }}"
        sequence: !input button_2_hold
      - conditions: "{{ command == '2_release' }}"
        sequence: !input button_2_release

      # Button 3
      - conditions: "{{ command == '3_single' }}"
        sequence: !input button_3_single
      - conditions: "{{ command == '3_double' }}"
        sequence: !input button_3_double
      - conditions: "{{ command == '3_hold' }}"
        sequence: !input button_3_hold
      - conditions: "{{ command == '3_release' }}"
        sequence: !input button_3_release

      # Button 4 (virtual)
      - conditions: "{{ command == '4_single' }}"
        sequence: !input button_4_single
      - conditions: "{{ command == '4_double' }}"
        sequence: !input button_4_double
      - conditions: "{{ command == '4_hold' }}"
        sequence: !input button_4_hold
      - conditions: "{{ command == '4_release' }}"
        sequence: !input button_4_release
