blueprint:
  name: Aqara H2 - 4 Button Switch (ZHA)
  description: >
    Handle all 4 buttons of the Aqara H2 (lumi.switch.agl006).
    Supports single, double, hold, and release actions per button.
  domain: automation
  input:
    switch_device:
      name: Aqara H2 switch
      description: The Aqara H2 Zigbee device
      selector:
        device:
          integration: zha

    # -------- BUTTON 1 --------
    button_1_single:
      name: Button 1 - Single press
      default: []
      selector:
        action: {}
    button_1_double:
      name: Button 1 - Double press
      default: []
      selector:
        action: {}
    button_1_hold:
      name: Button 1 - Hold
      default: []
      selector:
        action: {}
    button_1_release:
      name: Button 1 - Release
      default: []
      selector:
        action: {}

    # -------- BUTTON 2 --------
    button_2_single:
      name: Button 2 - Single press
      default: []
      selector:
        action: {}
    button_2_double:
      name: Button 2 - Double press
      default: []
      selector:
        action: {}
    button_2_hold:
      name: Button 2 - Hold
      default: []
      selector:
        action: {}
    button_2_release:
      name: Button 2 - Release
      default: []
      selector:
        action: {}

    # -------- BUTTON 3 --------
    button_3_single:
      name: Button 3 - Single press
      default: []
      selector:
        action: {}
    button_3_double:
      name: Button 3 - Double press
      default: []
      selector:
        action: {}
    button_3_hold:
      name: Button 3 - Hold
      default: []
      selector:
        action: {}
    button_3_release:
      name: Button 3 - Release
      default: []
      selector:
        action: {}

    # -------- BUTTON 4 --------
    button_4_single:
      name: Button 4 - Single press
      default: []
      selector:
        action: {}
    button_4_double:
      name: Button 4 - Double press
      default: []
      selector:
        action: {}
    button_4_hold:
      name: Button 4 - Hold
      default: []
      selector:
        action: {}
    button_4_release:
      name: Button 4 - Release
      default: []
      selector:
        action: {}

mode: restart

trigger:
  - platform: device
    domain: zha
    device_id: !input switch_device
    type: single
    subtype: button_1
  - platform: device
    domain: zha
    device_id: !input switch_device
    type: double
    subtype: button_1
  - platform: device
    domain: zha
    device_id: !input switch_device
    type: hold
    subtype: button_1
  - platform: device
    domain: zha
    device_id: !input switch_device
    type: release
    subtype: button_1

  - platform: device
    domain: zha
    device_id: !input switch_device
    type: single
    subtype: button_2
  - platform: device
    domain: zha
    device_id: !input switch_device
    type: double
    subtype: button_2
  - platform: device
    domain: zha
    device_id: !input switch_device
    type: hold
    subtype: button_2
  - platform: device
    domain: zha
    device_id: !input switch_device
    type: release
    subtype: button_2

  - platform: device
    domain: zha
    device_id: !input switch_device
    type: single
    subtype: button_3
  - platform: device
    domain: zha
    device_id: !input switch_device
    type: double
    subtype: button_3
  - platform: device
    domain: zha
    device_id: !input switch_device
    type: hold
    subtype: button_3
  - platform: device
    domain: zha
    device_id: !input switch_device
    type: release
    subtype: button_3

  - platform: device
    domain: zha
    device_id: !input switch_device
    type: single
    subtype: button_4
  - platform: device
    domain: zha
    device_id: !input switch_device
    type: double
    subtype: button_4
  - platform: device
    domain: zha
    device_id: !input switch_device
    type: hold
    subtype: button_4
  - platform: device
    domain: zha
    device_id: !input switch_device
    type: release
    subtype: button_4

action:
  - choose:
      # Button 1
      - conditions: "{{ trigger.subtype == 'button_1' and trigger.type == 'single' }}"
        sequence: !input button_1_single
      - conditions: "{{ trigger.subtype == 'button_1' and trigger.type == 'double' }}"
        sequence: !input button_1_double
      - conditions: "{{ trigger.subtype == 'button_1' and trigger.type == 'hold' }}"
        sequence: !input button_1_hold
      - conditions: "{{ trigger.subtype == 'button_1' and trigger.type == 'release' }}"
        sequence: !input button_1_release

      # Button 2
      - conditions: "{{ trigger.subtype == 'button_2' and trigger.type == 'single' }}"
        sequence: !input button_2_single
      - conditions: "{{ trigger.subtype == 'button_2' and trigger.type == 'double' }}"
        sequence: !input button_2_double
      - conditions: "{{ trigger.subtype == 'button_2' and trigger.type == 'hold' }}"
        sequence: !input button_2_hold
      - conditions: "{{ trigger.subtype == 'button_2' and trigger.type == 'release' }}"
        sequence: !input button_2_release

      # Button 3
      - conditions: "{{ trigger.subtype == 'button_3' and trigger.type == 'single' }}"
        sequence: !input button_3_single
      - conditions: "{{ trigger.subtype == 'button_3' and trigger.type == 'double' }}"
        sequence: !input button_3_double
      - conditions: "{{ trigger.subtype == 'button_3' and trigger.type == 'hold' }}"
        sequence: !input button_3_hold
      - conditions: "{{ trigger.subtype == 'button_3' and trigger.type == 'release' }}"
        sequence: !input button_3_release

      # Button 4
      - conditions: "{{ trigger.subtype == 'button_4' and trigger.type == 'single' }}"
        sequence: !input button_4_single
      - conditions: "{{ trigger.subtype == 'button_4' and trigger.type == 'double' }}"
        sequence: !input button_4_double
      - conditions: "{{ trigger.subtype == 'button_4' and trigger.type == 'hold' }}"
        sequence: !input button_4_hold
      - conditions: "{{ trigger.subtype == 'button_4' and trigger.type == 'release' }}"
        sequence: !input button_4_release
